footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
footprint_padding: 0.01
inflation_g:
    inflation_radius: 0.05
    
inflation_l:
    inflation_radius: 0.05

robot_base_frame: link_chassis
update_frequency: 2
publish_frequency: 1
transform_tolerance: 0.5

resolution: 0.05


 
obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: sensor_laser, data_type: LaserScan, topic: /amr_2wr/laser/scan, marking: true, clearing: true}



#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true




