obstacle_range: 5.5
raytrace_range: 6.0
footprint: [[-0.12, -0.12], [-0.12, 0.12], [0.12, 0.12], [0.12, -0.12]]
footprint_padding: 0.01
inflation_g:
    inflation_radius: 0.06
    
inflation_l:
    inflation_radius: 0.03

robot_base_frame: link_chassis
update_frequency: 2
publish_frequency: 1
transform_tolerance: 0.5

resolution: 0.05

obstacles_laser:
    observation_sources: scan
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

obstacle_layer:
    enabled: true
    obstacle_range: 5.0
    raytrace_range: 1.0
    observation_sources: scan
    observation_persistence: 0.0
    inf_is_valid: false
    scan:
      data_type: LaserScan
      topic: scan  

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true




